name: With Dependencies

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: running code
        run: |
          python create_output.py
          cat output.txt
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: output.txt
  check:
    needs: run
    runs-on: ubuntu-latest
    steps:
      - name: Download results
        uses: actions/download-artifact@v2
        with:
          name: results
      - name: checking
        run: |
          cat output.txt
